### ISSUE TITLE
how to draw

### ISSUE THREAD

**Issue by lloveapple** [shangxinyi/FEDIC#2]
Thank you very much for your excellent work. I would like to know what tool you used to draw the network diagram in the paper. Thank you very much.
good luck

**Comment by tuichong** [comment]
> Thank you very much for your excellent work. I would like to know what tool you used to draw the network diagram in the paper. Thank you very much. good luck

So,how to draw?

**Comment by lloveapple** [comment]
@tuichong PPT

**Comment by tuichong** [comment]
> @tuichong PPT

First of all, thank you for your answer. Have you reproduced this article? The result?
